[package]
name = "copar"
version = "0.1.0"
edition = "2021"
readme = "Readme.md"

[dependencies]
ordered-float = "0.5.0"
noindexmap = "1.6.1"
clap = { version = "4.5.38", features = ["derive"] }
stringcase = "0.4.0"
